version: '3'

services:

# rabbitmq: the rabbitmq server
 rabbitmq:
   image: 'rabbitmq:3.11.9-management-alpine'
   ports:
     - "5672:5672"
     - "15672:15672"
   deploy:
     mode: replicated
     replicas: 1
   volumes:
     - ./db-data/rabbitmq/:/var/lib/rabbitmq/

# # broker-service - main entry point; we call this from the front end
#  broker-service:
#    build:
#      context: .
#      dockerfile: ./broker-service.dockerfile
#    restart: always
#    ports:
#      - "8080:80"
#    deploy:
#      mode: replicated
#      replicas: 1
#    environment:
#      RABBIT_URL: "amqp://guest:guest@rabbitmq"

